db.recovery=db.recovery||[];db.profile.zoneMethod=db.profile.zoneMethod||'hrr';
const n=id=>$(id).value===''?null:+$(id).value,iso=d=>d.toISOString().slice(0,10),ld=x=>(+x.duration||0)*(+x.rpe||0);
function recDays(days,offset=0){let end=new Date();end.setDate(end.getDate()-offset);let start=new Date(end);start.setDate(start.getDate()-days+1);return db.sessions.filter(x=>new Date(x.date+'T12:00:00')>=start&&new Date(x.date+'T12:00:00')<=end)}
function loadMetrics(){let acute=recDays(7).reduce((a,x)=>a+ld(x),0),daily=[];for(let i=0;i<7;i++){let d=new Date();d.setDate(d.getDate()-i);daily.push(db.sessions.filter(x=>x.date===iso(d)).reduce((a,x)=>a+ld(x),0))}let mean=daily.reduce((a,x)=>a+x,0)/7,sd=Math.sqrt(daily.reduce((a,x)=>a+(x-mean)**2,0)/7),mon=sd?mean/sd:(acute?3:null),strain=mon?acute*mon:null,chronic=recDays(28,7).reduce((a,x)=>a+ld(x),0)/4;return{acute,mon,strain,acwr:chronic?acute/chronic:null}}
function renderLoad(){let m=loadMetrics(),status=m.acwr==null?'Sin base':m.acwr<=1.3?'Equilibrada':m.acwr<=1.5?'Elevada':'Muy elevada';$('loadCards').innerHTML=[['Carga 7 días',Math.round(m.acute),'min × RPE'],['Monotony',m.mon?.toFixed(2)||'—',m.mon>2?'Poca variedad':'Variación diaria'],['Strain',m.strain?Math.round(m.strain):'—','carga × monotony'],['Aguda/crónica',m.acwr?.toFixed(2)||'—',status]].map(x=>'<div class="card"><span class="muted">'+x[0]+'</span><strong style="display:block;font-size:23px">'+x[1]+'</strong><span class="tiny">'+x[2]+'</span></div>').join('')}
function zoneDefs(){let p=db.profile,max=+p.knownMaxHr||null,rest=+p.restHr||null;if(!max&&p.birthYear)max=208-.7*(new Date().getFullYear()-p.birthYear);if(!max)return null;return[[.5,.6],[.6,.7],[.7,.8],[.8,.9],[.9,1]].map((b,i)=>{let f=q=>p.zoneMethod==='hrr'&&rest?Math.round(rest+(max-rest)*q):Math.round(max*q);return{lo:f(b[0]),hi:f(b[1]),color:['#60a5fa','#22c55e','#eab308','#f97316','#ef4444'][i]}})}
function renderZones(){let z=zoneDefs();if(!z){$('zones').innerHTML='<p class="muted">Añade tu FC máxima en Perfil para calcular las zonas.</p>';return}let mins=[0,0,0,0,0],total=0;recDays(28).forEach(x=>{let a=[1,2,3,4,5].map(i=>+x['z'+i]||0),t=a.reduce((q,v)=>q+v,0);if(t){a.forEach((v,i)=>mins[i]+=v);total+=t}else if(x.hrAvg){let i=z.findIndex(q=>x.hrAvg>=q.lo&&x.hrAvg<=q.hi);i=i<0?(x.hrAvg<z[0].lo?0:4):i;mins[i]+=+x.duration||0;total+=+x.duration||0}});$('zones').innerHTML=z.map((q,i)=>'<div style="display:grid;grid-template-columns:35px 1fr 85px;gap:8px;align-items:center;margin:8px 0"><b style="color:'+q.color+'">Z'+(i+1)+'</b><div class="meter"><i style="width:'+(total?mins[i]/total*100:0)+'%;background:'+q.color+'"></i></div><span class="tiny">'+q.lo+'–'+q.hi+' ppm</span></div>').join('')+'<p class="tiny muted">Últimos 28 días. Se estima por FC media si faltan los minutos por zona.</p>'}
function renderPBs(){let run=db.sessions.filter(x=>['Running','Trail'].includes(x.activity)&&x.distance&&x.duration);$('pbs').innerHTML=[1,5,10,21.1,42.2].map(d=>{let x=run.filter(q=>Math.abs(q.distance-d)/d<=.04).sort((a,b)=>a.duration/a.distance-b.duration/b.distance)[0],name=d===21.1?'Media maratón':d===42.2?'Maratón':d+' km';return'<div class="item"><b>'+name+'</b><span style="float:right">'+(x?paceStr(x.duration/x.distance)+'/km · '+x.date:'—')+'</span></div>'}).join('')}
function ready(){let r=db.recovery.at(-1);if(!r)return null;let s=100,why=[];if(r.sleep&&r.sleep<7){s-=Math.min(20,(7-r.sleep)*8);why.push('sueño corto')}if(r.sleepQuality)s-=(5-r.sleepQuality)*5;if(r.fatigue){s-=(r.fatigue-1)*6;if(r.fatigue>=4)why.push('fatiga alta')}if(r.soreness){s-=(r.soreness-1)*6;if(r.soreness>=4)why.push('dolor muscular alto')}if(r.stress)s-=(r.stress-1)*4;if(r.motivation)s-=(5-r.motivation)*3;if(r.todayRestHr&&db.profile.restHr&&r.todayRestHr-db.profile.restHr>=7){s-=12;why.push('FC en reposo elevada')}return{score:Math.max(0,Math.round(s)),why}}
function renderRecovery(){let q=ready();$('readiness').innerHTML=!q?'<p class="muted">Completa un chequeo para obtener una lectura orientativa.</p>':'<div class="insight '+(q.score>=75?'good':q.score>=55?'warn':'alert')+'"><b>'+q.score+'/100 · '+(q.score>=75?'Buena disposición general':q.score>=55?'Ajusta la intensidad':'Prioriza recuperación')+'</b><div class="meter"><i style="width:'+q.score+'%"></i></div><p>'+(q.why.length?'Factores: '+q.why.join(', ')+'.':'Sin señales negativas destacadas.')+'</p><span class="tiny">No sustituye una valoración sanitaria.</span></div>';$('recoveryList').innerHTML=[...db.recovery].reverse().slice(0,8).map(x=>'<div class="item"><b>'+x.date+'</b> · sueño '+(x.sleep||'—')+' h · fatiga '+(x.fatigue||'—')+'/5 · dolor '+(x.soreness||'—')+'/5</div>').join('')||'<p class="muted">Aún no hay chequeos.</p>'}
const oldInsights=renderInsights;renderInsights=function(){oldInsights();let m=loadMetrics(),x='';if(m.acwr>1.5)x+='<div class="insight alert"><b>Incremento brusco de carga.</b> Reduce volumen o intensidad y revisa la recuperación.</div>';else if(m.acwr>1.3)x+='<div class="insight warn"><b>Carga elevada.</b> Evita encadenar otra sesión exigente si tu recuperación es baja.</div>';if(m.mon>2&&m.acute)x+='<div class="insight warn"><b>Semana monótona.</b> Alterna carga y descanso.</div>';let q=ready();if(q&&q.score<55)x+='<div class="insight alert">El último chequeo de recuperación es bajo: conviene ajustar el plan.</div>';$('insights').insertAdjacentHTML('afterbegin',x)}
const oldProfile=renderProfile;renderProfile=function(){oldProfile();$('birthYear').value=db.profile.birthYear||'';$('zoneMethod').value=db.profile.zoneMethod||'hrr'}
const oldRender=render;render=function(){oldRender();renderLoad();renderZones();renderPBs();renderRecovery()}
$('recDate').value=iso(new Date());$('recoveryForm').onsubmit=e=>{e.preventDefault();let x={date:$('recDate').value,sleep:n('sleep'),sleepQuality:n('sleepQuality'),fatigue:n('fatigue'),soreness:n('soreness'),stress:n('stress'),todayRestHr:n('todayRestHr'),motivation:n('motivation')};db.recovery=db.recovery.filter(r=>r.date!==x.date);db.recovery.push(x);db.recovery.sort((a,b)=>a.date.localeCompare(b.date));save();render();alert('Chequeo guardado')}
$('sessionForm').onsubmit=e=>{e.preventDefault();let d=+$('distance').value,t=+$('duration').value,z=[1,2,3,4,5].map(i=>n('z'+i)||0);db.sessions.push({id:Date.now().toString(36),date:$('date').value,activity:$('activity').value,sessionType:$('sessionType').value,distance:d,duration:t,avgPace:parsePace($('avgPace').value)||(d?t/d:null),maxPace:parsePace($('maxPace').value),cadence:n('cadence'),power:n('power'),vo2max:n('vo2max'),hrAvg:n('hrAvg'),hrMax:n('hrMax'),elevation:n('elevation'),rpe:n('rpe'),z1:z[0],z2:z[1],z3:z[2],z4:z[3],z5:z[4],notes:$('notes').value});db.sessions.sort((a,b)=>a.date.localeCompare(b.date));save();e.target.reset();$('date').value=iso(new Date());render();alert('Entrenamiento guardado')}
$('profileForm').onsubmit=e=>{e.preventDefault();db.profile.height=n('height');db.profile.restHr=n('restHr');db.profile.knownMaxHr=n('knownMaxHr');db.profile.birthYear=n('birthYear');db.profile.zoneMethod=$('zoneMethod').value;let w=n('weight');if(w)db.weights.push({date:iso(new Date()),weight:w});save();render();alert('Perfil actualizado')}
function csv2(rows){return '\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(';')).join('\n')}$('exportRecovery').onclick=()=>download('recuperacion-trainlab.csv',csv2([['fecha','sueno_h','calidad_sueno','fatiga','dolor','estres','fc_reposo','motivacion'],...db.recovery.map(x=>[x.date,x.sleep,x.sleepQuality,x.fatigue,x.soreness,x.stress,x.todayRestHr,x.motivation])]),'text/csv;charset=utf-8');
$('exportCsv').onclick=()=>download('entrenamientos-trainlab.csv',csv2([['fecha','actividad','tipo','distancia_km','tiempo_min','ritmo','cadencia','potencia_w','vo2max','fc_media','fc_max','desnivel','rpe','carga_srpe','z1','z2','z3','z4','z5','notas'],...db.sessions.map(x=>[x.date,x.activity,x.sessionType||'',x.distance,x.duration,paceStr(x.duration/x.distance),x.cadence,x.power,x.vo2max,x.hrAvg,x.hrMax,x.elevation,x.rpe,ld(x),x.z1,x.z2,x.z3,x.z4,x.z5,x.notes])]),'text/csv;charset=utf-8');
$('importJson').onchange=async e=>{try{let x=JSON.parse(await e.target.files[0].text());if(!Array.isArray(x.sessions)||typeof x.profile!=='object')throw 0;db={profile:{zoneMethod:'hrr'},weights:[],sessions:[],recovery:[],...x};db.recovery=db.recovery||[];save();render();alert('Datos importados')}catch{alert('Archivo no válido')}};
$('clearAll').onclick=()=>{if(confirm('Esto borrará todos los datos de este dispositivo.')){db={profile:{zoneMethod:'hrr'},weights:[],sessions:[],recovery:[]};save();render()}};render();
